### ISSUE TITLE
Signature Computation function returns NoneType

### ISSUE THREAD

**Issue by prashkmr** [BorgwardtLab/topological-autoencoders#7]
Hello,

Regarding the implementation of SignatureComputation() in surrogate_based.py  the forward() function doesn't return anything

class SignatureComputation(nn.Module):

This causes Line 66 to get NoneType value:

self.sig_comp = SignatureComputation(eps, dim)

leading to mismatch arguments at line 72 because the variable pers_x is NoneType.
Request you to please sort this out.

-Prashant

**Comment by mi92** [comment]
Hi Prashant,

thanks for catching this! Actually, the entire surrogate_based.py file is obsolete and should not be used.

Instead, all of the relevant TopoAE implementation you can find under approx_based.py

Best,
Michael
