### ISSUE TITLE
 multicoretsne

### ISSUE THREAD

**Issue by Chesuour** [BorgwardtLab/topological-autoencoders#9]
Good morning,sir:
         I am a Chinese student.I'm reading your article recently and I'm very interested in your research. But there is something wrong with the use of code.I can't install multicoretsne.The below is the information.

> Installing dependencies from Pipfile...

 >  ================================ 1/1 - 00:00:00
> An error occurred while installing multicoretsne==0.1! Will try again.
> Installing initially failed dependencies...
> [InstallError]:   File "d:\anaconda3\lib\site-packages\pipenv\cli\command.py", line 253, in install
> [InstallError]:       site_packages=state.site_packages
> [InstallError]:   File "d:\anaconda3\lib\site-packages\pipenv\core.py", line 2063, in do_install
> [InstallError]:       keep_outdated=keep_outdated
> [InstallError]:   File "d:\anaconda3\lib\site-packages\pipenv\core.py", line 1312, in do_init
> [InstallError]:       pypi_mirror=pypi_mirror,
> [InstallError]:   File "d:\anaconda3\lib\site-packages\pipenv\core.py", line 900, in do_install_dependencies
> [InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
> [InstallError]:   File "d:\anaconda3\lib\site-packages\pipenv\core.py", line 796, in batch_install
> [InstallError]:       _cleanup_procs(procs, failed_deps_queue, retry=retry)
> [InstallError]:   File "d:\anaconda3\lib\site-packages\pipenv\core.py", line 703, in _cleanup_procs
> [InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
> [pipenv.exceptions.InstallError]: Collecting multicoretsne==0.1
> [pipenv.exceptions.InstallError]:   Using cached MulticoreTSNE-0.1.tar.gz (20 kB)
> [pipenv.exceptions.InstallError]: Requirement already satisfied: numpy in c:\users\11\.virtualenvs\topological-autoencoders-> 

> master-0ayfqafo\lib\site-packages (from multicoretsne==0.1->-r c:\users\11\appdata\local\temp\pipenv-690j2s7

0-requirements\pipenv-7rw5i6kr-requirement.txt (line 1)) (1.20.3)

> [pipenv.exceptions.InstallError]: Requirement already satisfied: cffi in c:\users\11\.virtualenvs\topological-autoencoders-master-0ayfqafo\lib\site-packages (from multicoretsne==0.1->-r c:\users\11\appdata\local\temp\pipenv-690j2s70

> -requirements\pipenv-7rw5i6kr-requirement.txt (line 1)) (1.14.5)

> [pipenv.exceptions.InstallError]: Requirement already satisfied: pycparser in c:\users\11\.virtualenvs\topological-autoencoders-master-0ayfqafo\lib\site-packages (from cffi->multicoretsne==0.1->-r c:\users\11\appdata\local\temp\pipe
nv-690j2s70-requirements\pipenv-7rw5i6kr-requirement.txt (line 1)) (2.20)
> [pipenv.exceptions.InstallError]:** Building wheels for collected packages: multicoretsne
> [pipenv.exceptions.InstallError]:   Building wheel for multicoretsne (setup.py): started
> [pipenv.exceptions.InstallError]:   Building wheel for multicoretsne (setup.py): finished with status 'error'
> [pipenv.exceptions.InstallError]:   ERROR: Command errored out with exit status 1:
> [pipenv.exceptions.InstallError]:    command: 'C:\Users\11\.virtualenvs\topological-autoencoders-master-0aYfqAfO\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\11\\AppData\\Local\\
Temp\\pip-install-ynrf4fmk\\multicoretsne_89da54d44b404fda91ecb877e4c62a16\\setup.py'"'"'; __file__='"'"'C:\\Users\\11\\AppData\\Local\\Temp\\pip-install-ynrf4fmk\\multicoretsne_89da54d44b404fda91ecb877e4c62a16\\setup.py'"'"';f = ge
tattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file_
_, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\11\AppData\Local\Temp\pip-wheel-h6snep7e'
> [pipenv.exceptions.InstallError]:        cwd: C:\Users\11\AppData\Local\Temp\pip-install-ynrf4fmk\multicoretsne_89da54d44b404fda91ecb877e4c62a16\
> [pipenv.exceptions.InstallError]:   Complete output (29 lines):
> [pipenv.exceptions.InstallError]:   running bdist_wheel
> [pipenv.exceptions.InstallError]:   running build
> [pipenv.exceptions.InstallError]:   running build_py
> [pipenv.exceptions.InstallError]:   creating build
> [pipenv.exceptions.InstallError]:   creating build\lib.win-amd64-3.7
> [pipenv.exceptions.InstallError]:   creating build\lib.win-amd64-3.7\MulticoreTSNE
> [pipenv.exceptions.InstallError]:   copying MulticoreTSNE\__init__.py -> build\lib.win-amd64-3.7\MulticoreTSNE
> [pipenv.exceptions.InstallError]:   creating build\lib.win-amd64-3.7\MulticoreTSNE\tests
> [pipenv.exceptions.InstallError]:   copying MulticoreTSNE\tests\test_base.py -> build\lib.win-amd64-3.7\MulticoreTSNE\tests
> [pipenv.exceptions.InstallError]:   copying MulticoreTSNE\tests\__init__.py -> build\lib.win-amd64-3.7\MulticoreTSNE\tests
> [pipenv.exceptions.InstallError]:   running egg_info
> [pipenv.exceptions.InstallError]:   writing MulticoreTSNE.egg-info\PKG-INFO
> [pipenv.exceptions.InstallError]:   writing dependency_links to MulticoreTSNE.egg-info\dependency_links.txt
> [pipenv.exceptions.InstallError]:   writing requirements to MulticoreTSNE.egg-info\requires.txt
> [pipenv.exceptions.InstallError]:   writing top-level names to MulticoreTSNE.egg-info\top_level.txt
> [pipenv.exceptions.InstallError]:   reading manifest file 'MulticoreTSNE.egg-info\SOURCES.txt'
> [pipenv.exceptions.InstallError]:   reading manifest template 'MANIFEST.in'
> [pipenv.exceptions.InstallError]:   adding license file 'LICENSE.txt'
> [pipenv.exceptions.InstallError]:   writing manifest file 'MulticoreTSNE.egg-info\SOURCES.txt'
> [pipenv.exceptions.InstallError]:   warning: build_py: byte-compiling is disabled, skipping.
> [pipenv.exceptions.InstallError]:
> [pipenv.exceptions.InstallError]:   running build_ext
> [pipenv.exceptions.InstallError]:   cmake version 3.20.3
> [pipenv.exceptions.InstallError]:
> [pipenv.exceptions.InstallError]:   CMake suite maintained and supported by Kitware (kitware.com/cmake).
> [pipenv.exceptions.InstallError]:   CMake Error: Unknown argument --
> [pipenv.exceptions.InstallError]:   CMake Error: Run 'cmake --help' for all supported options.
> [pipenv.exceptions.InstallError]:
> [pipenv.exceptions.InstallError]:   ERROR: Cannot generate Makefile. See above errors.
> [pipenv.exceptions.InstallError]:   ----------------------------------------
> [pipenv.exceptions.InstallError]:   ERROR: Failed building wheel for multicoretsne
> [pipenv.exceptions.InstallError]:   Running setup.py clean for multicoretsne
> [pipenv.exceptions.InstallError]: Failed to build multicoretsne
> [pipenv.exceptions.InstallError]: Installing collected packages: multicoretsne
> [pipenv.exceptions.InstallError]:     Running setup.py install for multicoretsne: started
> [pipenv.exceptions.InstallError]:     Running setup.py install for multicoretsne: finished with status 'error'
> [pipenv.exceptions.InstallError]:     ERROR: Command errored out with exit status 1:
> [pipenv.exceptions.InstallError]:      command: 'C:\Users\11\.virtualenvs\topological-autoencoders-master-0aYfqAfO\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\11\\AppData\\Local
\\Temp\\pip-install-ynrf4fmk\\multicoretsne_89da54d44b404fda91ecb877e4c62a16\\setup.py'"'"'; __file__='"'"'C:\\Users\\11\\AppData\\Local\\Temp\\pip-install-ynrf4fmk\\multicoretsne_89da54d44b404fda91ecb877e4c62a16\\setup.py'"'"';f =
getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __fil
e__, '"'"'exec'"'"'))' install --record 'C:\Users\11\AppData\Local\Temp\pip-record-8yv_r9yl\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\11\.virtualenvs\topological-autoencoders-maste
r-0aYfqAfO\include\site\python3.7\multicoretsne'
> [pipenv.exceptions.InstallError]:          cwd: C:\Users\11\AppData\Local\Temp\pip-install-ynrf4fmk\multicoretsne_89da54d44b404fda91ecb877e4c62a16\
> [pipenv.exceptions.InstallError]:     Complete output (29 lines):
> [pipenv.exceptions.InstallError]:     running install
> [pipenv.exceptions.InstallError]:     running build
> [pipenv.exceptions.InstallError]:     running build_py
> [pipenv.exceptions.InstallError]:     creating build
> [pipenv.exceptions.InstallError]:     creating build\lib.win-amd64-3.7
> [pipenv.exceptions.InstallError]:     creating build\lib.win-amd64-3.7\MulticoreTSNE
> [pipenv.exceptions.InstallError]:     copying MulticoreTSNE\__init__.py -> build\lib.win-amd64-3.7\MulticoreTSNE
> [pipenv.exceptions.InstallError]:     creating build\lib.win-amd64-3.7\MulticoreTSNE\tests
> [pipenv.exceptions.InstallError]:     copying MulticoreTSNE\tests\test_base.py -> build\lib.win-amd64-3.7\MulticoreTSNE\tests
> [pipenv.exceptions.InstallError]:     copying MulticoreTSNE\tests\__init__.py -> build\lib.win-amd64-3.7\MulticoreTSNE\tests
> [pipenv.exceptions.InstallError]:     running egg_info
> [pipenv.exceptions.InstallError]:     writing MulticoreTSNE.egg-info\PKG-INFO
> [pipenv.exceptions.InstallError]:     writing dependency_links to MulticoreTSNE.egg-info\dependency_links.txt
> [pipenv.exceptions.InstallError]:     writing requirements to MulticoreTSNE.egg-info\requires.txt
> [pipenv.exceptions.InstallError]:     writing top-level names to MulticoreTSNE.egg-info\top_level.txt
> [pipenv.exceptions.InstallError]:     reading manifest file 'MulticoreTSNE.egg-info\SOURCES.txt'
> [pipenv.exceptions.InstallError]:     reading manifest template 'MANIFEST.in'
> [pipenv.exceptions.InstallError]:     adding license file 'LICENSE.txt'
> [pipenv.exceptions.InstallError]:     writing manifest file 'MulticoreTSNE.egg-info\SOURCES.txt'
> [pipenv.exceptions.InstallError]:     warning: build_py: byte-compiling is disabled, skipping.
> [pipenv.exceptions.InstallError]:
> [pipenv.exceptions.InstallError]:     running build_ext
> [pipenv.exceptions.InstallError]:     cmake version 3.20.3
> [pipenv.exceptions.InstallError]:
> [pipenv.exceptions.InstallError]:     CMake suite maintained and supported by Kitware (kitware.com/cmake).
> [pipenv.exceptions.InstallError]:     CMake Error: Unknown argument --
> [pipenv.exceptions.InstallError]:     CMake Error: Run 'cmake --help' for all supported options.
> [pipenv.exceptions.InstallError]:
> [pipenv.exceptions.InstallError]:     ERROR: Cannot generate Makefile. See above errors.
> [pipenv.exceptions.InstallError]:     ----------------------------------------
> [pipenv.exceptions.InstallError]: ERROR: Command errored out with exit status 1: 'C:\Users\11\.virtualenvs\topological-autoencoders-master-0aYfqAfO\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '
"'"'C:\\Users\\11\\AppData\\Local\\Temp\\pip-install-ynrf4fmk\\multicoretsne_89da54d44b404fda91ecb877e4c62a16\\setup.py'"'"'; __file__='"'"'C:\\Users\\11\\AppData\\Local\\Temp\\pip-install-ynrf4fmk\\multicoretsne_89da54d44b404fda91e
cb877e4c62a16\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f
.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\11\AppData\Local\Temp\pip-record-8yv_r9yl\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\11\.virtualen
vs\topological-autoencoders-master-0aYfqAfO\include\site\python3.7\multicoretsne' Check the logs for full command output.
ERROR: Couldn't install package: multicoretsne
>  Package installation failed...
     ================================ 0/1 - 00:00:03`

**Comment by Pseudomanifold** [comment]
Thanks for raising this issue. This problem is *not* caused by our code but by an upstream package called [multicoretsne](https://github.com/DmitryUlyanov/Multicore-TSNE). The error message indicates that your `CMake`installation has a problem in handling an argument in the installation instructions. See [issue #81 of the multicoretsne package](https://github.com/DmitryUlyanov/Multicore-TSNE/issues/81) for more details. I see two potential workarounds:

1. Remove the dependency and build the package without it.
2. Downgrade your `CMake` installation.

Hope that helps!

**Comment by Chesuour** [comment]
Thank you,I run sucessfully!
